project:
  type: book
  output-dir: docs
  # render:
    # - index.qmd
    # - intro.qmd
    # - C01_intro.qmd
    # - C01_univar.qmd
    # - C01_corr.qmd
    # - C01_dist.qmd
    # - C02_episteme.qmd
    # - C02_muestreo.qmd
    # - C02_estim.qmd
    # - C02_tamano.qmd
    # - C02_hipotesis.qmd

book:
  title: "Estadística para Ciencias Sociales"
  author: 
   - "Nestor Rojas"
   - "Raquel Ortega"
   - "Miguel Mendez"
   - "Julián Cruz"
  cover-image: 05_img/cover.png
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - C99_todo.qmd
    - autores.qmd
    - part: C01_cover.qmd
      chapters:
        - C01_prelim.qmd
        - C01_prepara.qmd
        - C01_univar.qmd
        - C01_corr.qmd
        - C01_dist.qmd
        - C01_vis.qmd
    - part: C02_cover.qmd
      chapters:
        - C02_episteme.qmd
        - C02_muestreo.qmd
        - C02_estim.qmd
        - C02_tamano.qmd
        - C02_hipotesis.qmd
        - C02_pruebas.qmd
    - part: C03_cover.qmd
      chapters:
        - C03_abordaje.qmd
        - C03_modelamiento.qmd
        - C03_reg-lineal.qmd
        - C03_reg-logit.qmd
        - C03_medicion.qmd
        - C03_acp.qmd
    - part: C04_cover.qmd
      chapters:
        - C04_enfoque.qmd
        - 04_est-multi.qmd

format:
  html:
    theme: litera
    css: styles.css
  pdf: default

bibliography: biblio.bibtex
csl: apa.csl

